trigger:
  batch: true
  branches:
      include:
      - develop
      - devops/*

variables:
  vmImage: 'ubuntu-20.04'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: $(vmImage)
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 14'
        inputs:
          versionSpec: 14.x
          checkLatest: true
      - task: Npm@1
        displayName: 'Installing NPM packages'
        inputs: 
          command: custom
          workingDir: expressApp
          verbose: false
          customCommand: 'ci'
      - task: Npm@1
        displayName: 'Creating DB schema'
        inputs: 
          command: custom
          workingDir: expressApp
          verbose: false
          customCommand: 'run db'
      - task: CopyFiles@2
        displayName: 'Copy Files to Target Folder'
        inputs:
          SourceFolder: expressApp
          TargetFolder: $(Build.ArtifactStagingDirectory)\FilesToPublish\expressApp
      - task: CopyFiles@2
        displayName: 'Copy Files to Target Folder'
        inputs:
          SourceFolder: devops\terraform
          TargetFolder: $(Build.ArtifactStagingDirectory)\FilesToPublish\terraform
      - task: ArchiveFiles@2
        displayName: 'Archiving app files into artifact'
        inputs:
          rootFolderOrFile: $(Build.ArtifactStagingDirectory)\FilesToPublish
      - task: PublishBuildArtifacts@1
        displayName: 'Publishing artifact'
        inputs:
          artifactName: 'drop'
