trigger:
  batch: true
  branches:
    include:
    - master

pr: none

pool:
  vmImage: ubuntu-20.04

steps:
  - task: NodeTool@0
    displayName: 'Use Node 14'
    inputs:
      versionSpec: 14.x
      checkLatest: true
  - task: Npm@1
    displayName: 'Installing NPM packages'
    inputs: 
      command: custom
      workingDir: expressApp
      verbose: false
      customCommand: 'ci'
  - task: Npm@1
    displayName: 'Creating DB schema'
    inputs: 
      command: custom
      workingDir: expressApp
      verbose: false
      customCommand: 'run db'
  - task: Npm@1
    displayName: 'Running E2E tests'
    inputs: 
      command: custom
      workingDir: expressApp
      verbose: false
      customCommand: 'run test'
  - task: CopyFiles@2
    inputs:
      sourceFolder: expressApp
      targetFolder: $(Build.ArtifactStagingDirectory)/artifact
  - task: CopyFiles@2
    inputs:
      sourceFolder: devops/terraform
      targetFolder: $(Build.ArtifactStagingDirectory)/artifact/terraform
  - task: ArchiveFiles@2
    displayName: 'Archiving files'
    inputs: 
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)/artifact/
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/artifact/drop.zip
      archiveType: zip
  - task: PublishBuildArtifacts@1
    displayName: 'Publishing files'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/artifact
      artifactName: drop.zip
